name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: holepunchto/actions/.github/steps/setup-repo@v1
      - run: npm i
      - run: npm t
